server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy → Service Chambres (Python/Flask)
    location /api/chambres {
        proxy_pass         http://service-chambres:5001/chambres;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        add_header         X-Served-By "service-chambres (Python/Flask)";
    }

    # Proxy → Service Reservation (Node.js/Express)
    location /api/reservations {
        proxy_pass         http://service-reservation:5002/reservations;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        add_header         X-Served-By "service-reservation (Node.js/Express)";
    }

    # Health checks
    location /api/health/chambres {
        proxy_pass http://service-chambres:5001/health;
    }
    location /api/health/reservations {
        proxy_pass http://service-reservation:5002/health;
    }

    # ── NOUVEAU : Interface admin service-chambres ──────────
    location /admin {
        proxy_pass       http://service-chambres:5001/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── NOUVEAU : API directe pour l'interface admin ────────
    # L'admin JS appelle /chambres (pas /api/chambres)
    location /chambres {
        proxy_pass       http://service-chambres:5001/chambres;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}