apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-frontend-hpa
  namespace: hotel
  labels:
    app.kubernetes.io/name: hotel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.hpa.frontend.minReplicas }}
  maxReplicas: {{ .Values.hpa.frontend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.frontend.cpuThreshold }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-chambres-hpa
  namespace: hotel
  labels:
    app.kubernetes.io/name: hotel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-chambres
  minReplicas: {{ .Values.hpa.serviceChambres.minReplicas }}
  maxReplicas: {{ .Values.hpa.serviceChambres.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.serviceChambres.cpuThreshold }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-reservation-hpa
  namespace: hotel
  labels:
    app.kubernetes.io/name: hotel
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-reservation
  minReplicas: {{ .Values.hpa.serviceReservation.minReplicas }}
  maxReplicas: {{ .Values.hpa.serviceReservation.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.serviceReservation.cpuThreshold }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
